//
// Created by Evgeniy on 12.10.2022.
//
#ifndef INFSECLINEARCONGRUENTIALGENERATOR_LINEARCONGRUENTIALGENERATOR_H
#define INFSECLINEARCONGRUENTIALGENERATOR_LINEARCONGRUENTIALGENERATOR_H

void encrypt(const char* plaintext, char* ciphertext);

void decrypt(const char* ciphertext, char* decrypted_text);

#endif //INFSECLINEARCONGRUENTIALGENERATOR_LINEARCONGRUENTIALGENERATOR_H
